name: covid_tracker
description: A flutter project for guidelines regarding covid19

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_screen: ^1.0.0
  intl: ^0.16.1
  # flutter_bloc: ^3.2.0
  dio: ^3.0.9
  # equatable: ^1.1.1
  line_icons: ^0.2.0
  shimmer: ^1.1.0
  # shared_preferences: ^0.5.6+2
  webview_flutter: ^0.3.19+9
  built_value: ^7.0.9
  built_collection: ^4.3.2
  # http: ^0.12.0+4
  url_launcher: ^5.4.2
  flutter_spinkit: 4.1.2
  google_nav_bar: ^2.0.1
  google_fonts: 0.2.0

  #
  get_it: ^4.0.1
  dartz: ^0.8.6
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.6+3
  flutter_launcher_icons: ^0.7.4

  flutter_bloc: ^0.21.0
  equatable: ^0.4.0
  http: ^0.12.0+2

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

# flutter_icons:
#   image_path: "assets/icons/final_icon.png"
#   android: true
#   ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:

  #For creating mock tests
  mockito: ^4.1.0

# flutter:
#   uses-material-design: true
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg

# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700

flutter:
  uses-material-design: true
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/Questrial-Regular.ttf
